# Generated by Django 5.1.1 on 2024-10-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20241008_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='desc',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='thumb_url',
            field=models.URLField(default=None),
        ),
    ]
