# Generated by Django 5.1.1 on 2024-10-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_videodata_desc_alter_videodata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='channelId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='channelTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
