# Generated by Django 5.1.1 on 2024-10-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_videodata_channelid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
